### ISSUE TITLE
Not apply link in official GSoD page

### ISSUE THREAD

**Issue by zriyansh** [mautic/Gsod#3]
Just to make things clear, Google does not accept proposals (unlike done in GSoC), the orgs accept, review and select candidates based on who's proposal they feel suits the need, the readme file is confusing, kindly correct it.

**Comment by RCheesley** [comment]
Hi there,

You just need to drop us an email at seasonofdocs@mautic.org per the instructions here: https://github.com/mautic/Gsod#get-started.

Thanks!

**Comment by zriyansh** [comment]
Sorry to open this issue again, but it would be really nice of you if you could inform us about the deadline for proposal sending as Google does not give any specific deadline for it, that's for organizations to decide.

I asked it in the slack channel, seems people are quite busy. Thanks @RCheesley @olawanlejoel
